ethereum_rpc = "https://rpc.hoodi.ethpandaops.io"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.high_volume_trade_alert]
path = "out/HighVolumeTradeAlert.sol/HighVolumeTradeAlert.json"
response_contract = "0x6E354f4284E20404d6623a616da7C503666ac057"
response_function = "respondCallback(uint256)"
cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 10
private_trap = true
whitelist = ["0x8f381fc797CAA2E1a754fCaA323DeeD3BBAAE115"]
address = "0x751ecc4c5e06c8aF87f5b4F9a8F937a6EC50D057"
